<div class="form-grid"><label>Etiqueta<input name="label" value="{{ old('label', $address->label ?? '') }}" placeholder="Casa, oficina..." required></label><label>Destinatario<input name="recipient_name" value="{{ old('recipient_name', $address->recipient_name ?? auth()->user()->name) }}" required></label><label>Teléfono<input name="phone" value="{{ old('phone', $address->phone ?? auth()->user()->phone) }}" required></label></div>
<label>Dirección<input name="line_one" value="{{ old('line_one', $address->line_one ?? '') }}" required></label><label>Interior o complemento<input name="line_two" value="{{ old('line_two', $address->line_two ?? '') }}"></label>
<div class="form-grid"><label>Distrito<select name="district" required><option value="">Selecciona un distrito</option>@foreach($districts as $district)<option value="{{ $district }}" @selected(old('district', $address->district ?? '') === $district)>{{ $district }}</option>@endforeach</select></label><label>Provincia<input name="province" value="Ica" readonly required></label><label>Departamento<input name="department" value="Ica" readonly required></label></div>
<label>Referencia<textarea name="reference">{{ old('reference', $address->reference ?? '') }}</textarea></label>
<div class="address-map-section"><div><h3>Ubicación aproximada</h3><p>Opcional: toca el punto exacto. Ayuda al repartidor, pero no reemplaza la dirección escrita.</p></div><button type="button" class="map-location-button" data-use-location>Usar mi ubicación</button></div>
<input type="hidden" name="latitude" value="{{ old('latitude', $address->latitude ?? '') }}"><input type="hidden" name="longitude" value="{{ old('longitude', $address->longitude ?? '') }}">
<div class="address-map" data-address-map data-latitude="{{ old('latitude', $address->latitude ?? -14.0678) }}" data-longitude="{{ old('longitude', $address->longitude ?? -75.7286) }}" data-has-location="{{ old('latitude', $address->latitude ?? null) !== null ? '1' : '0' }}" data-tile-url="{{ config('maps.tile_url') }}" data-attribution="{{ config('maps.attribution') }}"></div>
<small class="map-help" data-map-status>Haz clic en el mapa para fijar la ubicación.</small>
<label class="check-field"><input type="checkbox" name="is_default" value="1" @checked(old('is_default', $address->is_default ?? false))> Usar como dirección predeterminada</label>
