<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('users', fn (Blueprint $t) => [$t->id(), $t->string('name'), $t->string('email')->unique(), $t->string('phone', 30)->nullable(), $t->timestamp('email_verified_at')->nullable(), $t->string('password'), $t->boolean('is_active')->default(true), $t->rememberToken(), $t->timestamps(), $t->softDeletes()]);
        Schema::create('password_reset_tokens', fn (Blueprint $t) => [$t->string('email')->primary(), $t->string('token'), $t->timestamp('created_at')->nullable()]);
        Schema::create('sessions', fn (Blueprint $t) => [$t->string('id')->primary(), $t->foreignId('user_id')->nullable()->index(), $t->string('ip_address', 45)->nullable(), $t->text('user_agent')->nullable(), $t->longText('payload'), $t->integer('last_activity')->index()]);
        Schema::create('personal_access_tokens', fn (Blueprint $t) => [$t->id(), $t->morphs('tokenable'), $t->text('name'), $t->string('token', 64)->unique(), $t->text('abilities')->nullable(), $t->timestamp('last_used_at')->nullable(), $t->timestamp('expires_at')->nullable()->index(), $t->timestamps()]);
        Schema::create('categories', fn (Blueprint $t) => [$t->id(), $t->foreignId('parent_id')->nullable()->constrained('categories')->nullOnDelete(), $t->string('name'), $t->string('slug')->unique(), $t->text('description')->nullable(), $t->boolean('is_active')->default(true), $t->unsignedInteger('sort_order')->default(0), $t->timestamps(), $t->softDeletes()]);
        Schema::create('products', fn (Blueprint $t) => [$t->id(), $t->foreignId('category_id')->nullable()->constrained()->nullOnDelete(), $t->string('name'), $t->string('slug')->unique(), $t->text('short_description')->nullable(), $t->longText('description')->nullable(), $t->boolean('is_active')->default(true), $t->boolean('is_featured')->default(false), $t->string('meta_title')->nullable(), $t->text('meta_description')->nullable(), $t->timestamps(), $t->softDeletes()]);
        Schema::create('product_variants', fn (Blueprint $t) => [$t->id(), $t->foreignId('product_id')->constrained()->cascadeOnDelete(), $t->string('name'), $t->string('sku')->unique(), $t->unsignedTinyInteger('cacao_percentage')->nullable(), $t->unsignedInteger('weight_grams'), $t->unsignedBigInteger('price_amount'), $t->unsignedBigInteger('promotional_price_amount')->nullable(), $t->unsignedInteger('stock')->default(0), $t->unsignedInteger('low_stock_threshold')->default(5), $t->boolean('is_active')->default(true), $t->timestamps(), $t->softDeletes()]);
        Schema::create('product_images', fn (Blueprint $t) => [$t->id(), $t->foreignId('product_id')->constrained()->cascadeOnDelete(), $t->foreignId('product_variant_id')->nullable()->constrained()->nullOnDelete(), $t->string('path'), $t->string('alt_text')->nullable(), $t->boolean('is_primary')->default(false), $t->unsignedInteger('sort_order')->default(0), $t->timestamps()]);
        Schema::create('addresses', fn (Blueprint $t) => [$t->id(), $t->foreignId('user_id')->constrained()->cascadeOnDelete(), $t->string('label'), $t->string('recipient_name'), $t->string('phone', 30), $t->string('line_one'), $t->string('line_two')->nullable(), $t->string('district'), $t->string('province'), $t->string('department'), $t->text('reference')->nullable(), $t->decimal('latitude', 10, 7)->nullable(), $t->decimal('longitude', 10, 7)->nullable(), $t->boolean('is_default')->default(false), $t->timestamps(), $t->softDeletes()]);
        Schema::create('delivery_zones', fn (Blueprint $t) => [$t->id(), $t->string('name'), $t->json('districts'), $t->boolean('is_active')->default(true), $t->timestamps()]);
        Schema::create('delivery_rates', fn (Blueprint $t) => [$t->id(), $t->foreignId('delivery_zone_id')->constrained()->cascadeOnDelete(), $t->unsignedBigInteger('amount'), $t->unsignedBigInteger('free_from_amount')->nullable(), $t->boolean('is_active')->default(true), $t->timestamps()]);
        Schema::create('payment_methods', fn (Blueprint $t) => [$t->id(), $t->string('code')->unique(), $t->string('name'), $t->text('instructions')->nullable(), $t->boolean('requires_proof')->default(false), $t->boolean('is_active')->default(true), $t->timestamps()]);
        Schema::create('coupons', fn (Blueprint $t) => [$t->id(), $t->string('code')->unique(), $t->enum('type', ['fixed', 'percentage']), $t->unsignedBigInteger('value'), $t->unsignedBigInteger('minimum_amount')->nullable(), $t->unsignedBigInteger('maximum_discount_amount')->nullable(), $t->unsignedInteger('usage_limit')->nullable(), $t->unsignedInteger('usage_count')->default(0), $t->timestamp('starts_at')->nullable(), $t->timestamp('ends_at')->nullable(), $t->boolean('is_active')->default(true), $t->timestamps(), $t->softDeletes()]);
        Schema::create('order_statuses', fn (Blueprint $t) => [$t->id(), $t->string('code')->unique(), $t->string('name'), $t->boolean('is_terminal')->default(false), $t->unsignedInteger('sort_order')->default(0), $t->timestamps()]);
        Schema::create('orders', fn (Blueprint $t) => [$t->id(), $t->uuid('number')->unique(), $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(), $t->foreignId('order_status_id')->constrained(), $t->foreignId('payment_method_id')->constrained(), $t->string('customer_name'), $t->string('customer_email'), $t->string('customer_phone', 30), $t->json('delivery_address'), $t->unsignedBigInteger('subtotal_amount'), $t->unsignedBigInteger('discount_amount')->default(0), $t->unsignedBigInteger('delivery_amount')->default(0), $t->unsignedBigInteger('total_amount'), $t->string('coupon_code')->nullable(), $t->string('payment_proof_path')->nullable(), $t->text('customer_note')->nullable(), $t->timestamps()]);
        Schema::create('order_items', fn (Blueprint $t) => [$t->id(), $t->foreignId('order_id')->constrained()->cascadeOnDelete(), $t->foreignId('product_variant_id')->nullable()->constrained()->nullOnDelete(), $t->string('product_name'), $t->string('variant_name'), $t->string('sku'), $t->text('description')->nullable(), $t->unsignedBigInteger('unit_price_amount'), $t->unsignedInteger('quantity'), $t->unsignedBigInteger('line_total_amount'), $t->timestamps()]);
        Schema::create('order_status_histories', fn (Blueprint $t) => [$t->id(), $t->foreignId('order_id')->constrained()->cascadeOnDelete(), $t->foreignId('order_status_id')->constrained(), $t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete(), $t->text('note')->nullable(), $t->timestamps()]);
        Schema::create('inventory_movements', fn (Blueprint $t) => [$t->id(), $t->foreignId('product_variant_id')->constrained(), $t->foreignId('order_id')->nullable()->constrained()->nullOnDelete(), $t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete(), $t->string('type'), $t->integer('quantity_delta'), $t->unsignedInteger('balance_after'), $t->text('reason')->nullable(), $t->timestamps()]);
        Schema::create('carts', fn (Blueprint $t) => [$t->id(), $t->foreignId('user_id')->nullable()->constrained()->cascadeOnDelete(), $t->uuid('token')->unique(), $t->timestamp('expires_at')->nullable(), $t->timestamps()]);
        Schema::create('cart_items', fn (Blueprint $t) => [$t->id(), $t->foreignId('cart_id')->constrained()->cascadeOnDelete(), $t->foreignId('product_variant_id')->constrained(), $t->unsignedInteger('quantity'), $t->timestamps(), $t->unique(['cart_id', 'product_variant_id'])]);
        Schema::create('banners', fn (Blueprint $t) => [$t->id(), $t->string('title'), $t->text('body')->nullable(), $t->string('image_path'), $t->string('button_label')->nullable(), $t->string('button_url')->nullable(), $t->timestamp('starts_at')->nullable(), $t->timestamp('ends_at')->nullable(), $t->boolean('is_active')->default(true), $t->unsignedInteger('sort_order')->default(0), $t->timestamps()]);
        Schema::create('faqs', fn (Blueprint $t) => [$t->id(), $t->string('question'), $t->text('answer'), $t->boolean('is_active')->default(true), $t->unsignedInteger('sort_order')->default(0), $t->timestamps()]);
        Schema::create('business_settings', fn (Blueprint $t) => [$t->id(), $t->string('key')->unique(), $t->json('value')->nullable(), $t->timestamps()]);
        Schema::create('contact_requests', fn (Blueprint $t) => [$t->id(), $t->string('name'), $t->string('email'), $t->string('phone', 30)->nullable(), $t->string('subject'), $t->text('message'), $t->string('status')->default('new'), $t->text('internal_note')->nullable(), $t->timestamps()]);
    }

    public function down(): void
    {
        foreach (array_reverse(['users', 'password_reset_tokens', 'sessions', 'personal_access_tokens', 'categories', 'products', 'product_variants', 'product_images', 'addresses', 'delivery_zones', 'delivery_rates', 'payment_methods', 'coupons', 'order_statuses', 'orders', 'order_items', 'order_status_histories', 'inventory_movements', 'carts', 'cart_items', 'banners', 'faqs', 'business_settings', 'contact_requests']) as $table) {
            Schema::dropIfExists($table);
        }
    }
};
