param([string]$ToolsRoot = (Join-Path $PSScriptRoot '..\.tools'))
$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'
$ToolsRoot = [IO.Path]::GetFullPath($ToolsRoot); $downloads = Join-Path $ToolsRoot 'downloads'
New-Item -ItemType Directory -Force -Path $ToolsRoot,$downloads | Out-Null
function Get-VerifiedFile([string]$Uri,[string]$Path,[string]$ExpectedHash) { Invoke-WebRequest -UseBasicParsing -Uri $Uri -OutFile $Path; $actual=(Get-FileHash -Algorithm SHA256 $Path).Hash.ToLowerInvariant(); if($actual -ne $ExpectedHash.ToLowerInvariant()){throw "Checksum mismatch for $Uri"} }
$phpUri='https://downloads.php.net/~windows/releases/php-8.2.32-Win32-vs16-x64.zip'; $phpZip=Join-Path $downloads 'php-8.2.32-x64.zip'
$phpHash='b3985f246bc925fe5722769bb7402a68979a0b6487456691e24aa948ad2f38c5'; Get-VerifiedFile $phpUri $phpZip $phpHash
$phpRoot=Join-Path $ToolsRoot 'php-8.2'; if(Test-Path $phpRoot){Remove-Item -Recurse -Force $phpRoot}; Expand-Archive $phpZip $phpRoot
Copy-Item (Join-Path $phpRoot 'php.ini-development') (Join-Path $phpRoot 'php.ini'); $ini=Get-Content (Join-Path $phpRoot 'php.ini') -Raw; $ini=$ini.Replace(';extension_dir = "ext"','extension_dir = "ext"')
foreach($extension in 'curl','fileinfo','intl','mbstring','openssl','pdo_mysql','pdo_sqlite','sqlite3','zip'){$ini=$ini -replace ";extension=$extension","extension=$extension"}; $ini+="`r`ndate.timezone=America/Lima`r`nmemory_limit=512M`r`n"; Set-Content -Encoding ASCII (Join-Path $phpRoot 'php.ini') $ini
$composerPath=Join-Path $ToolsRoot 'composer.phar'; Get-VerifiedFile 'https://getcomposer.org/download/2.10.2/composer.phar' $composerPath '5ee7125f8a30a34d246cefdc0bc85b8a783b28f2aec968994118512350d28027'; Set-Content -Encoding ASCII (Join-Path $ToolsRoot 'composer.cmd') "@echo off`r`n`"$phpRoot\php.exe`" `"$composerPath`" %*`r`n"
$nodeVersion='22.23.1'; $nodeName="node-v$nodeVersion-win-x64.zip"; $sums=(Invoke-WebRequest -UseBasicParsing "https://nodejs.org/download/release/v$nodeVersion/SHASUMS256.txt").Content; $nodeHash=((($sums -split "`n")|Where-Object{$_ -match [regex]::Escape($nodeName)})-split '\s+')[0]; $nodeZip=Join-Path $downloads $nodeName; Get-VerifiedFile "https://nodejs.org/download/release/v$nodeVersion/$nodeName" $nodeZip $nodeHash
$nodeExtract=Join-Path $ToolsRoot "node-v$nodeVersion-win-x64"; if(Test-Path $nodeExtract){Remove-Item -Recurse -Force $nodeExtract}; Expand-Archive $nodeZip $ToolsRoot; $nodeRoot=Join-Path $ToolsRoot 'node'; if(Test-Path $nodeRoot){Remove-Item -Recurse -Force $nodeRoot}; Rename-Item $nodeExtract $nodeRoot
$release=Invoke-RestMethod -Headers @{Accept='application/vnd.github+json';'User-Agent'='cacao-local-setup'} 'https://api.github.com/repos/git-for-windows/git/releases/latest'; $asset=$release.assets|Where-Object{$_.name -match '^MinGit-[0-9.]+-64-bit\.zip$'}|Select-Object -First 1; if(-not $asset){throw 'Could not locate MinGit x64.'}; $gitHash=($asset.digest -replace '^sha256:',''); if(-not $gitHash){throw 'GitHub did not publish the Git asset digest.'}; $gitZip=Join-Path $downloads $asset.name; Get-VerifiedFile $asset.browser_download_url $gitZip $gitHash; $gitRoot=Join-Path $ToolsRoot 'git'; if(Test-Path $gitRoot){Remove-Item -Recurse -Force $gitRoot}; Expand-Archive $gitZip $gitRoot
$activation="`$tools='$ToolsRoot'`r`n`$env:PATH=`"`$tools\php-8.2;`$tools;`$tools\node;`$tools\git\cmd;`$tools\git\mingw64\bin;`$env:PATH`"`r`n`$env:PHPRC=`"`$tools\php-8.2`"`r`n`$env:COMPOSER_HOME=`"`$tools\composer-home`"`r`n"; Set-Content -Encoding UTF8 (Join-Path $ToolsRoot 'activate.ps1') $activation; . (Join-Path $ToolsRoot 'activate.ps1')
php --version; composer --version; node --version; npm --version; git --version
